from pathlib import Path

DATA_DIR = Path("data")

RAW_DATA_DIR = DATA_DIR / "01_raw"
RAW_DATA_FILE = RAW_DATA_DIR / "data.parquet"

__TRAIN_FILE = "train.parquet"
__EVAL_FILE = "eval.parquet"
__TEST_FILE = "test.parquet"

SPLIT_DATA_DIR = DATA_DIR / "02_split"
SPLIT_TRAIN_FILE = SPLIT_DATA_DIR / __TRAIN_FILE
SPLIT_EVAL_FILE = SPLIT_DATA_DIR / __EVAL_FILE
SPLIT_TEST_FILE = SPLIT_DATA_DIR / __TEST_FILE

MODEL_INPUT_DATA_DIR = DATA_DIR / "03_model_input"
TRAIN_DATA_FILE = MODEL_INPUT_DATA_DIR / __TRAIN_FILE
EVAL_DATA_FILE = MODEL_INPUT_DATA_DIR / __EVAL_FILE
TEST_DATA_FILE = MODEL_INPUT_DATA_DIR / __TEST_FILE

MODEL_DATA_DIR = DATA_DIR / "04_models"

FINAL_MODEL_PATH = Path("models")
